language: node_js
node_js:
  - "0.10"

script: "npm test && npm run coveralls"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dd893be75c6b9908987d
    on_success: change
    on_failure: always
    on_start:   never
